apiVersion: infra.ctf.school/v1
kind: LabService
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: labservice-sample
spec:
  # TODO(user): Add fields here
