apiVersion: lab.ctf.school/v1
kind: LabNode
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: labnode-sample
spec:
  # TODO(user): Add fields here
